name: Vérification de la structure du schéma et de la validité de l'exemple

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Installation des dépendances
      run: pip install -r requirements.txt

    - run: python .github/workflows/integrity_check.py